#
# Core Integrations
#

homeassistant:
  name: Home
  unit_system: metric
  time_zone: !secret home_timezone
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0

# Enables a map showing the location of tracked devices
map:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables configuration UI
config:
