#
# Bedroom Light
#

light:
  - platform: mqtt
    name: Bedroom Light
    command_topic: cmnd/IR_Bridge/IRSEND
    payload_on: '{"Protocol":"NEC","Bits":32,"Data":"0x41B645BA"}'
    payload_off: '{"Protocol":"NEC","Bits":32,"Data":"0x41B67D82"}'
    optimistic: true

  - platform: mqtt
    name: Bedroom Brightness
    command_topic: cmnd/IR_Bridge/IRSEND
    payload_on: '{"Protocol":"NEC","Bits":32,"Data":"0x41B65DA2"}'
    payload_off: '{"Protocol":"NEC","Bits":32,"Data":"0x41B6DD22"}'
    optimistic: true

  - platform: mqtt
    name: Bedroom Night Light
    command_topic: cmnd/IR_Bridge/IRSEND
    payload_on: '{"Protocol":"NEC","Bits":32,"Data":"0x41B63DC2"}'
    payload_off: '{"Protocol":"NEC","Bits":32,"Data":"0x41B67D82"}'
    optimistic: true

#
# Simulate 3-way toggle switch
#
automation:
  - alias: Turn light off when night light is on
    trigger:
      platform: state
      entity_id: light.bedroom_night_light
      from: "off"
      to: "on"
    action:
      service: python_script.set_state
      data:
        entity_id: light.bedroom_light
        state: "off"

  - alias: Turn night light off when light is on
    trigger:
      platform: state
      entity_id: light.bedroom_light
      from: "off"
      to: "on"
    action:
      service: python_script.set_state
      data:
        entity_id: light.bedroom_night_light
        state: "off"
