#
# Closet Sensor Door
#

mqtt:
  binary_sensor:
    - name: Closet Door
      state_topic: zigbee2mqtt/Closet_SensorDoor
      value_template: '{{ value_json.contact }}'
      payload_on: false
      payload_off: true
      device_class: door

    - name: Closet Door Battery Low
      state_topic: zigbee2mqtt/Closet_SensorDoor
      value_template: '{{ value_json.battery_low }}'
      payload_on: true
      payload_off: false
      device_class: battery

  sensor:
    - name: Closet Door Battery
      state_topic: zigbee2mqtt/Closet_SensorDoor
      value_template: '{{ value_json.battery }}'
      unit_of_measurement: '%'
      device_class: battery

automation:
  #
  # Switch on Closet Light when Closet Door is opened
  #
  - alias: Switch on Closet Light when Closet Door is opened
    trigger:
      platform: state
      entity_id: binary_sensor.closet_door
      from: "off"
      to: "on"
    action:
      service: switch.turn_on
      target:
        entity_id: switch.closet_light

  #
  # Switch off Closet Light when Closet Door is closed
  #
  - alias: Switch off Closet Light when Closet Door is closed
    trigger:
      platform: state
      entity_id: binary_sensor.closet_door
      from: "on"
      to: "off"
    action:
      service: switch.turn_off
      target:
        entity_id: switch.closet_light
