#
# Living Room TV
#

media_player:
  - platform: smartir
    name: Living Room TV Device
    unique_id: living_room_tv_device
    device_code: 8888
    controller_data: cmnd/IR_Bridge/IRSEND

#
# Additional Features via scripts
#
  - platform: universal
    name: Living Room TV
    retain: true
    children:
      - media_player.living_room_tv_device
    commands:
      turn_on:
        service: script.living_room_tv_turn_on
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.living_room_tv_plug
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.living_room_tv_device
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.living_room_tv_device
      volume_mute:
        service: media_player.volume_mute
        data_template:
          entity_id: media_player.living_room_tv_device
          is_volume_muted: "{{ not state_attr('media_player.living_room_tv_device', 'is_volume_muted') }}"
      select_source:
        service: python_script.tv_change_source
        data_template:
          source: '{{ source }}'
    attributes:
      state: media_player.living_room_tv_device
      source: sensor.living_room_tv_source
      source_list: media_player.living_room_tv_device|source_list

#
# Set Media Player as TV
#
homeassistant:
  customize:
    media_player.living_room_tv:
      device_class: tv

#
# Preserve source input
#
mqtt:
  sensor:
    - name: Living Room TV Source
      state_topic: homeassistant/media_player/living_room_tv
      value_template: "{{ value_json.source }}"

#
# TV Switch On Combo
#
script:
  living_room_tv_turn_on:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.living_room_tv_plug
      - delay:
          seconds: 10
      - service: media_player.turn_on
        data:
          entity_id: media_player.living_room_tv_device
