#
# Room Plug
#

switch:
  - platform: mqtt
    name: Room TV Plug
    command_topic: cmnd/Plug_Room/POWER2
    state_topic: stat/Plug_Room/POWER2
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt
    name: Room Console Plug
    command_topic: cmnd/Plug_Room/POWER1
    state_topic: stat/Plug_Room/POWER1
    payload_on: "ON"
    payload_off: "OFF"

#
# Energy Consumption Sensors
#
sensor:
  - platform: mqtt
    name: Room Plug Power
    state_topic: tele/Plug_Room/SENSOR
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: W
  - platform: mqtt
    name: Room Plug Energy Today
    state_topic: tele/Plug_Room/SENSOR
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: kWh
  - platform: mqtt
    name: Room Plug Energy Yesterday
    state_topic: tele/Plug_Room/SENSOR
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    unit_of_measurement: kWh
  - platform: mqtt
    name: Room Plug Energy Total
    state_topic: tele/Plug_Room/SENSOR
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    unit_of_measurement: kWh

#
# Set TV State to Off when switch is turned off
#
automation:
  - alias: Set TV state to Off when switch is turned off
    trigger:
      platform: state
      entity_id: switch.room_tv_plug
      from: "on"
      to: "off"
    action:
      service: media_player.turn_off
      data:
        entity_id: media_player.room_tv_device
