#
# Room Sensor
#

mqtt:
  sensor:
    - name: Room Temperature
      state_topic: tele/Sensor_Room/SENSOR
      value_template: '{{ value_json["SCD40"]["Temperature"] }}'
      unit_of_measurement: °C
    - name: Room Humidity
      state_topic: tele/Sensor_Room/SENSOR
      value_template: '{{ value_json["SCD40"]["Humidity"] }}'
      unit_of_measurement: '%'
    - name: Room Dew Point
      state_topic: tele/Sensor_Room/SENSOR
      value_template: '{{ value_json["SCD40"]["DewPoint"] }}'
      unit_of_measurement: °C
    - name: Room Carbon Dioxide
      state_topic: tele/Sensor_Room/SENSOR
      value_template: '{{ value_json["SCD40"]["CarbonDioxide"] }}'
      unit_of_measurement: ppm


#
# Let homekit recognize humidity sensor
#
homeassistant:
  customize:
    sensor.room_humidity:
      device_class: humidity

    sensor.room_carbon_dioxide:
      device_class: carbon_dioxide


#
# Notify if humidity is below threshold
#

# Presence Detection powered by Homekit
input_boolean:
  adwin_present:
    name: Adwin
    icon: mdi:account
  shiuan_present:
    name: Shiuan
    icon: mdi:account

automation:
  - alias: Notify Adwin if humidity is low
    trigger:
      - platform: state
        entity_id: input_boolean.adwin_present
        from: "off"
        to: "on"
      - platform: time_pattern
        minutes: "/30"
    condition:
      - condition: time
        after: "09:00:00"
        before: "23:59:59"
      - condition: state
        entity_id: input_boolean.adwin_present
        state: "on"
      - condition: numeric_state
        entity_id:
          - sensor.room_humidity
        below: 50
    action:
      - service: notify.mobile_app_iadwin
        data:
          title: Low Humidity
          message: "Room humidity is now at {{ states('sensor.room_humidity') }}%"

  - alias: Notify Shiuan if humidity is low
    trigger:
      - platform: state
        entity_id: input_boolean.shiuan_present
        from: "off"
        to: "on"
      - platform: time_pattern
        minutes: "/30"
    condition:
      - condition: time
        after: "09:00:00"
        before: "23:59:59"
      - condition: state
        entity_id: input_boolean.shiuan_present
        state: "on"
      - condition: numeric_state
        entity_id:
          - sensor.room_humidity
        below: 50
    action:
      - service: notify.mobile_app_sws
        data:
          title: Low Humidity
          message: "Room humidity is now at {{ states('sensor.room_humidity') }}%"
