#
# Room Vacuum
#

mqtt:
  vacuum:
    - name: Dave
      supported_features:
        - battery
        - status
        - start
        - stop
        - pause
        - return_home
        - fan_speed
        - locate
      state_topic: valetudo/Dave/hass/Dave_vacuum/state
      command_topic: valetudo/Dave/hass/Dave_vacuum/command
      payload_start: START
      payload_pause: PAUSE
      payload_return_to_base: HOME
      payload_stop: STOP
      payload_locate: LOCATE
      set_fan_speed_topic: valetudo/Dave/FanSpeedControlCapability/preset/set
      fan_speed_list:
        - low
        - medium
        - high
        - max
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

  select:
    - name: Dave Mode
      icon: mdi:developer-board
      entity_category: config
      state_topic: valetudo/Dave/OperationModeControlCapability/preset
      value_template: "{{ value }}"
      command_topic: valetudo/Dave/OperationModeControlCapability/preset/set
      options:
        - vacuum
        - mop
        - vacuum_and_mop
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

    - name: Dave Water Usage
      icon: mdi:water-pump
      entity_category: config
      state_topic: valetudo/Dave/WaterUsageControlCapability/preset
      value_template: "{{ value }}"
      command_topic: valetudo/Dave/WaterUsageControlCapability/preset/set
      options:
        - low
        - medium
        - high
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

  number:
    - name: Dave Speaker Volume
      icon: mdi:volume-source
      entity_category: config
      state_topic: valetudo/Dave/SpeakerVolumeControlCapability/value
      command_topic: valetudo/Dave/SpeakerVolumeControlCapability/value/set
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

  binary_sensor:
    - name: Dave Mop Attachment
      entity_category: diagnostic
      state_topic: valetudo/Dave/AttachmentStateAttribute/mop
      payload_off: "false"
      payload_on: "true"
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

  sensor:
    - name: Dave Battery Level
      icon: mdi:battery
      entity_category: diagnostic
      device_class: battery
      state_topic: valetudo/Dave/BatteryStateAttribute/level
      unit_of_measurement: "%"
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

    - name: Dave Events
      icon: mdi:bell
      state_topic: valetudo/Dave/hass/Dave_sensor_ValetudoEvents
      json_attributes_topic: valetudo/Dave/ValetudoEvents/valetudo_events
      json_attributes_template: "{{ value }}"
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost

  # For homekit
  switch:
    - name: Dave Vacuum
      state_topic: valetudo/Dave/hass/Dave_vacuum/state
      value_template: "{{ value_json.state }}"
      state_on: cleaning
      state_off: docked
      command_topic: valetudo/Dave/hass/Dave_vacuum/command
      payload_on: START
      payload_off: HOME
      availability_topic: valetudo/Dave/$state
      payload_available: ready
      payload_not_available: lost


script:
  dave_spot_cleaning:
    icon: mdi:play-box
    alias: Dave Start Spot Cleaning
    fields:
      targets:
        name: Cleaning Targets
        required: true
        selector:
          select:
            multiple: true
            custom_value: false
            options:
              - label: Hallway
                value: "3"
              - label: Kitchen
                value: "2"
              - label: Bathroom
                value: "1"
              - label: Workspace
                value: "6"
              - label: Living Room
                value: "7"
              - label: Bedroom
                value: "5"
      iterations:
        name: Iterations
        required: true
        default: "1"
        selector:
          select:
            multiple: false
            custom_value: false
            options:
              - "1"
              - "2"
              - "3"
              - "4"
    sequence:
      - service: mqtt.publish
        data:
          topic: valetudo/Dave/MapSegmentationCapability/clean/set
          payload_template: '{ "segment_ids": [{{ targets | join(",") }}], "iterations": {{ iterations }} }'

#
# Schedule cleaning
#
automation:
  - alias: Start vacuum at 9:30AM eveery Monday, Wednesday, Friday
    trigger:
      platform: time
      at: "09:30:00"
    condition:
      condition: time
      weekday:
        - mon
        - wed
        - fri
    action:
      - service: vacuum.start
        data:
          entity_id: vacuum.dave
