#
# Room Sensor
#

sensor:
  - platform: mqtt
    name: Room Temperature
    state_topic: tele/Sensor_Room/SENSOR
    value_template: '{{ value_json["BME280"]["Temperature"] }}'
    unit_of_measurement: °C
  - platform: mqtt
    name: Room Humidity
    state_topic: tele/Sensor_Room/SENSOR
    value_template: '{{ value_json["BME280"]["Humidity"] }}'
    unit_of_measurement: '%'
  - platform: mqtt
    name: Room Dew Point
    state_topic: tele/Sensor_Room/SENSOR
    value_template: '{{ value_json["BME280"]["DewPoint"] }}'
    unit_of_measurement: °C
  - platform: mqtt
    name: Room Pressure
    state_topic: tele/Sensor_Room/SENSOR
    value_template: '{{ value_json["BME280"]["Pressure"] }}'
    unit_of_measurement: hPa


#
# Let homekit recognize humidity sensor
#
homeassistant:
  customize:
    sensor.room_humidity:
      device_class: humidity
