#
# Toilet Sensor Motion
#

mqtt:
  binary_sensor:
    - name: Toilet Motion
      state_topic: zigbee2mqtt/Toilet_SensorMotion
      value_template: '{{ value_json.occupancy }}'
      payload_on: true
      payload_off: "VOID"
      off_delay: 130
      device_class: motion

    - name: Toilet Motion Battery Low
      entity_category: diagnostic
      state_topic: zigbee2mqtt/Toilet_SensorMotion
      value_template: '{{ value_json.battery_low }}'
      payload_on: true
      payload_off: false
      device_class: battery

  sensor:
    - name: Toilet Motion Battery
      entity_category: diagnostic
      state_class: measurement
      state_topic: zigbee2mqtt/Toilet_SensorMotion
      value_template: '{{ value_json.battery }}'
      unit_of_measurement: '%'
      device_class: battery

automation:
  - alias: Switch on Toilet Light and Ventilation when Toilet Motion is detected
    trigger:
      platform: state
      entity_id: binary_sensor.toilet_motion
      from: "off"
      to: "on"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.toilet_light
      - service: switch.turn_on
        target:
          entity_id: switch.toilet_ventilation

  - alias: Switch off Toilet Light and Ventilation when Toilet Motion is not detected
    trigger:
      platform: state
      entity_id: binary_sensor.toilet_motion
      from: "on"
      to: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.toilet_light
      - service: switch.turn_off
        target:
          entity_id: switch.toilet_ventilation
